name: wjkc.lol Automatic Daily Check-in (Final MD5 Version)

on:
  schedule:
    # 北京时间每天早上8点10分执行 (UTC时间 00:10)
    - cron: '10 0 * * *'
  # 允许在Actions页面手动触发
  workflow_dispatch:

jobs:
  checkin-job:
    runs-on: ubuntu-latest
    env:
      # 在你的仓库 Settings > Secrets and variables > Actions 中设置以下密钥
      # 这是我们最终确认的多账户方案，请按需设置
      USER1: ${{ secrets.USER1 }}
      PASS1: ${{ secrets.PASS1 }}
      USER2: ${{ secrets.USER2 }}
      PASS2: ${{ secrets.PASS2 }}
      USER3: ${{ secrets.USER3 }}
      PASS3: ${{ secrets.PASS3 }}
      # ...可以一直添加下去

      # Telegram推送是可选的，如果不需要可以留空
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # 我们只需要最基础的requests库
      - name: Install Python Dependencies
        run: pip install requests
          
      # 运行我们最终的、完美的自动化脚本
      - name: Run the Final Check-in Script
        run: python auto_checkin.py