name: wjkc.lol Automatic Daily Check-in (Requests)

on:
  schedule:
    - cron: '10 0 * * *' # 北京时间每天早上8点10分
  workflow_dispatch:

jobs:
  checkin-job:
    runs-on: ubuntu-latest
    env:
      USER1: ${{ secrets.USER1 }}
      PASS1: ${{ secrets.PASS1 }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.9' }
      # 我们只需要安装requests
      - name: Install Python Dependencies
        run: pip install requests
      - name: Run the Check-in Script
        run: python auto_checkin.py