name: wjkc.lol Automatic Daily Check-in

on:
  workflow_dispatch: # 我们暂时只保留手动触发，方便您测试
  schedule:
    - cron: '10 0 * * *' # 北京时间每天早上8点10分

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      USER1: ${{ secrets.USER1 }}
      PASS1: ${{ secrets.PASS1 }}

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.9' }
      - name: Install Google Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - name: Install Python Dependencies
        run: pip install selenium webdriver-manager
      - name: Run Check-in Script
        run: python auto_checkin.py