name: wjkc.lol Automatic Daily Check-in (Correct Multi-Account)

on:
  schedule:
    - cron: '10 0 * * *' # 北京时间每天早上8点10分
  workflow_dispatch:

jobs:
  checkin-job:
    runs-on: ubuntu-latest
    env:
      # --- 推荐的多账户配置方式 ---
      # 在仓库的Secrets中，创建一个名为 WJKC_TOKENS (注意是复数) 的Secret。
      # 将您所有的Cookie值，用【英文逗号(,)】分隔，然后粘贴到这一个Secret里。
      # 例如: token_value_1,token_value_2,token_value_3
      WJKC_TOKENS: ${{ secrets.WJKC_TOKENS }}
      
      # --- Telegram推送 (所有账户共用) ---
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.9' }
      - run: pip install requests
      - run: python auto_checkin.py